### ISSUE TITLE
Confirmation email after registration

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/events.backdropcms.org#13]
Several users have reported that they did not get confirmation emails after registering.

**Comment by indigoxela** [comment]
Is this about the confirmation mail by Paypal, or is there an additional one?

I did receive the mail from Paypal - the sender address may vary depending on country. I didn't receive any other confirmation, nor see any message after payment success. So "technically" I'm not sure if my registration worked properly - I just assume that. :smile: 

If it's about Paypal mails, then maybe the first thing to check in your/their mail client is the spam folder.

**Comment by jackaponte** [comment]
> Is this about the confirmation mail by Paypal, or is there an additional one?

I think this is about a registration confirmation sent from the Backdrop site itself.

Tim, I noticed that on https://events.backdropcms.org/admin/config/system/smtp the SMTP module is turned off; could that have something to do with this problem?

Otherwise this seems like it might be a server-side issue, since the Registration module looks properly configured to send emails to me.

**Comment by indigoxela** [comment]
FTR: the welcome message arrived today morning without any problem. :+1:

**Comment by stpaultim** [comment]
This issue is old and I am unaware of recent instances of this happening. Will close this issue and reopen later if needed.
